apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namespace: three-tier

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: three-tier-ebs

  resources:
    requests:
      storage: 10Gi